# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BreakingBadCharacters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BreakingBadCharacters

  target 'BreakingBadCharactersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BreakingBadCharactersUITests' do
    # Pods for testing
  end

end
